allowBuilds:
  '@tailwindcss/oxide': false
  core-js: false
  esbuild: false
  msw: false
  sharp: false
  unrs-resolver: false
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - inotify
  - msw
  - sharp
  - unrs-resolver
